services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/book
    depends_on:
      - database
      - php

  php:
    container_name: app
    restart: unless-stopped
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/book

  database:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3366:3306"
    env_file:
      - docker/database.env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: